#!/bin/bash
printf "dropping db\n";
dropdb -p ${PGPORT} -h ${PGHOST} -U ${PGUSER} --if-exists -e ${PGDATABASE};
printf "\nCreating db\n"
createdb -p ${PGPORT} -h ${PGHOST} -U ${PGUSER} -e ${PGDATABASE}
printf "\nLoading db schema\n"
psql -p ${PGPORT} -h ${PGHOST} -U ${PGUSER} -f ./db/schema.sql