#!/bin/bash
printf "dropping db\n";
dropdb -p ${PGPORT} -h ${HOST} -U ${PGUSER} --if-exists -e ${PGDATABASE};
printf "\nCreating db\n"
createdb -p ${PGPORT} -h ${HOST} -U ${PGUSER} -e ${PGDATABASE}
printf "\nLoading db schema\n"
psql -p ${PGPORT} -h ${HOST} -U ${PGUSER} -f ./db/schema.sql
printf "\nLoading db seeds\n"
psql -p ${PGPORT} -h ${HOST} -U ${PGUSER} -f ./db/seeds.sql
